default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", "") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "template_app_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "template_app_test") %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "template_app_production") %>
    username: <%= ENV.fetch("DB_USERNAME", "template_app") %>
    password: <%= ENV["DB_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME", "template_app_production") %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME", "template_app_production") %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME", "template_app_production") %>_cable
    migrations_paths: db/cable_migrate
